name: wow100
description: "WoW100 is a Flutter application that helps users track their progress in World of Warcraft. It provides features for tracking various in-game activities, such as quests, achievements, and character progression. The app is designed to be user-friendly and visually appealing, making it easy for players to stay organized and motivated in their WoW journey."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/data/mounts/
    - assets/data/pets/
    - assets/images/expansions/
